const menuData = [
  {
    "id": "mars-latte",
    "category": "Espresso Bazlı",
    "name": "Mars Latte",
    "description": "Yumuşak içimli espresso, süt ve hafif karamel dokunuşu.",
    "price": 115,
    "sizes": [],
    "tags": ["Önerilen", "Sütlü", "Sıcak"],
    "isPopular": true,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "kizil-gezegen-mocha",
    "category": "Espresso Bazlı",
    "name": "Kızıl Gezegen Mocha",
    "description": "Espresso, çikolata ve süt ile yoğun ama dengeli bir lezzet.",
    "price": 125,
    "sizes": [],
    "tags": ["Çikolatalı", "Sütlü"],
    "isPopular": true,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "espresso",
    "category": "Espresso Bazlı",
    "name": "Espresso",
    "description": "Yoğun aromalı klasik espresso shot.",
    "price": 70,
    "sizes": [],
    "tags": ["Sert", "Sıcak"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "americano",
    "category": "Espresso Bazlı",
    "name": "Americano",
    "description": "Espresso ve sıcak su ile sade, dengeli kahve.",
    "price": 85,
    "sizes": [],
    "tags": ["Sade", "Sıcak"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "cappuccino",
    "category": "Espresso Bazlı",
    "name": "Cappuccino",
    "description": "Espresso, buharla ısıtılmış süt ve yoğun süt köpüğü.",
    "price": 105,
    "sizes": [],
    "tags": ["Sütlü", "Sıcak"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "latte",
    "category": "Espresso Bazlı",
    "name": "Latte",
    "description": "Espresso ve bol süt ile yumuşak içimli klasik.",
    "price": 110,
    "sizes": [],
    "tags": ["Sütlü", "Sıcak"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "mocha",
    "category": "Espresso Bazlı",
    "name": "Mocha",
    "description": "Espresso, süt ve çikolatanın sıcak birleşimi.",
    "price": 120,
    "sizes": [],
    "tags": ["Çikolatalı", "Sütlü"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "filtre-kahve",
    "category": "Filtre Kahveler",
    "name": "Filtre Kahve",
    "description": "Günün çekirdeğiyle hazırlanan sade ve aromatik kahve.",
    "price": 90,
    "sizes": [],
    "tags": ["Sade", "Sıcak"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "v60",
    "category": "Filtre Kahveler",
    "name": "V60",
    "description": "Daha berrak ve katmanlı aroma profili sunan demleme.",
    "price": 120,
    "sizes": [],
    "tags": ["Demleme", "Sade"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "ice-americano",
    "category": "Soğuk Kahveler",
    "name": "Ice Americano",
    "description": "Espresso, soğuk su ve buz ile ferah sade kahve.",
    "price": 95,
    "sizes": [],
    "tags": ["Soğuk", "Sade"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "ice-latte",
    "category": "Soğuk Kahveler",
    "name": "Ice Latte",
    "description": "Espresso, soğuk süt ve buz ile yumuşak içim.",
    "price": 115,
    "sizes": [],
    "tags": ["Soğuk", "Sütlü"],
    "isPopular": true,
    "isNew": false,
    "allergens": ["Süt içerir"],
    "available": true
  },
  {
    "id": "cold-brew",
    "category": "Soğuk Kahveler",
    "name": "Cold Brew",
    "description": "Uzun süre soğuk demleme ile düşük asiditeli kahve.",
    "price": 130,
    "sizes": [],
    "tags": ["Soğuk", "Sade"],
    "isPopular": false,
    "isNew": false,
    "allergens": [],
    "available": true
  },
  {
    "id": "brownie",
    "category": "Tatlılar",
    "name": "Brownie",
    "description": "Yoğun çikolatalı, kahve yanında ideal tatlı.",
    "price": 95,
    "sizes": [],
    "tags": ["Tatlı"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Gluten içerebilir"],
    "available": true
  },
  {
    "id": "cheesecake",
    "category": "Tatlılar",
    "name": "Cheesecake",
    "description": "Hafif kremamsı dokulu günlük tatlı seçeneği.",
    "price": 110,
    "sizes": [],
    "tags": ["Tatlı"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Süt içerir", "Gluten içerebilir"],
    "available": true
  },
  {
    "id": "kruvasan",
    "category": "Atıştırmalıklar",
    "name": "Kruvasan",
    "description": "Tereyağlı, hafif ve kahveyle uyumlu klasik seçenek.",
    "price": 85,
    "sizes": [],
    "tags": ["Atıştırmalık"],
    "isPopular": false,
    "isNew": false,
    "allergens": ["Gluten içerir"],
    "available": true
  }
];

const categories = [
  "Tümü",
  "Popüler",
  "Espresso Bazlı",
  "Filtre Kahveler",
  "Soğuk Kahveler",
  "Tatlılar",
  "Atıştırmalıklar"
];
